### ISSUE TITLE
Check the below screen shot make pagination like that

### ISSUE THREAD

**Issue by sharath7178** [Nimble-Institute/nimble-design-system#113]
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/c6907910-2134-4f4c-bb9c-a2e730f26156)

**Comment by Manoj201** [comment]
@sharath7178  added below prop
<img width="495" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/700f5850-52f7-4075-9cac-a692965fd0dc">
