### ISSUE TITLE
data table user data should have font weight 300

### ISSUE THREAD

**Issue by sharath7178** [Nimble-Institute/nimble-design-system#114]
https://www.figma.com/file/hVPAUt74BDJZgTzB8kQ4qn/NRF?node-id=1025%3A19634&mode=dev

**Comment by Manoj201** [comment]
@sharath7178 This issue was fixed.
<img width="927" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/4c1d7980-de6a-42ea-8eec-dde6a34625a2">

**Comment by Manoj201** [comment]
@NimbleMax @sharath7178 @rajeshswain424 
All font weights come from shared types.

type fontWeight = '300' | '400' | '500' | '600' | '700';

**Comment by NimbleMax** [comment]
Yeah it should not be an option, we always have the same fontweight. Please look in the design system on how we build up the variables.

**Comment by Manoj201** [comment]
@sharath7178 @NimbleMax Ok Noted. I will remove the dataFontWeight always for 300.
and fill remove the dataFontWeight prop.

**Comment by Manoj201** [comment]
@sharath7178  as we discussed removed data font-weight prop and added default 300
