### ISSUE TITLE
In below screen shot have close icon in nimble select field, for that icon send one props for show and hide in the field because if select field required means no need show close icon  

### ISSUE THREAD

**Issue by sharath7178** [Nimble-Institute/nimble-design-system#132]
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/4fad7543-a87a-4f60-bfc4-3843848a9023)

**Comment by Manoj201** [comment]
@sharath7178 
added isEnableClear prop, the default value is true. If you pass it false clear icon will disappear.
Thanks
