### ISSUE TITLE
if enter a number in pagination text field after click on the go to button it should reflect in the pagination number check below screen shot

### ISSUE THREAD

**Issue by sharath7178** [Nimble-Institute/nimble-design-system#136]
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/c5438398-47a7-49b5-a514-9aa7a8b24a51)
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/4fa09d2a-7449-4ca0-b595-5aecfd0385cd)

**Comment by Manoj201** [comment]
Invalid bug
@sharath7178 
we are not keeping pagination data on the local state, it's working on props, Of you enter any specific page number and press Go --> it will execute your parent component handler function. At that time you have to call API with the entered page number. Then change paginationData prop based on that and it will automatically appear on the table.
