### ISSUE TITLE
Implement Calendar Timeline Chart

### ISSUE THREAD

**Issue by Manoj201** [Nimble-Institute/nimble-design-system#15]
@anuja01 Can you please add a simple description and screenshot?

**Comment by anuja01** [comment]
<img width="994" alt="Screenshot 2023-07-21 at 5 19 31 PM" src="https://github.com/Nimble-Institute/nimble-design-system/assets/23234889/0b25f11a-4c78-499e-9010-405976ccceed">

**Comment by Manoj201** [comment]
@anuja01 @NimbleMax This task was done and released yesterday.  So closing this. Thanks
