### ISSUE TITLE
Nimble File Uploader 

### ISSUE THREAD

**Issue by rasaralaya-nimble-expert** [Nimble-Institute/nimble-design-system#159]
![the three buttons at the bottom must have the option of appearing on hover in addition to appearing on click](https://github.com/Nimble-Institute/nimble-design-system/assets/145844108/53fe98a6-0fd2-427b-9bbb-b75d806f027c)

**currently**
- the preview/download, edit, and delete buttons show only on-clicking the file preview image

**required**
- it should be possible to pass a prop to make the preview/download, edit, and delete buttons appear on hovering over the preview files instead of an on-click

**Comment by Manoj201** [comment]
@rasaralaya-nimble-expert Added new prop for this feature
<img width="914" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/751b0e70-23e5-4ab9-9039-9e7d09bfbf63">

**Comment by rasaralaya-nimble-expert** [comment]
there is an issue with the on hover, the options for action like preview/download, edit, and delete disappear before it can be clicked on
