### ISSUE TITLE
can you add one prop for adding and removing the filter icon in data table and also it should effect on filter fields also

### ISSUE THREAD

**Issue by sharath7178** [Nimble-Institute/nimble-design-system#212]
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/f6cf7947-690b-41b2-a413-555582904514)

**Comment by anuja01** [comment]
@sharath7178 Now, the filter icon and filter headers will be only visible if the `onChangeColumnFilters` callback is passed.
