### ISSUE TITLE
color prop for data grid search and filter options 

### ISSUE THREAD

**Issue by rasaralaya-nimble-expert** [Nimble-Institute/nimble-design-system#238]
![nimble-data-grid-colors](https://github.com/Nimble-Institute/nimble-design-system/assets/145844108/955849ef-a08a-4d12-821d-9297af879e50)

**Existing**: 
search tasks field and the option fields are all transparent and hence getting the same color as the backdrop

**Expected**:
search tasks field and filter option fields must have color customizable with props

**Comment by Manoj201** [comment]
close this no more valid this
