### ISSUE TITLE
row actions column does not behave responsively

### ISSUE THREAD

**Issue by rasaralaya-nimble-expert** [Nimble-Institute/nimble-design-system#276]
![rowAction-for-table-is-not-responsive](https://github.com/Nimble-Institute/nimble-design-system/assets/145844108/c386b639-94b3-4acc-b2a7-758aa1301151)

**Current**
Row Action icons column take up constant width space and do not scale down responsively as the width of the screen reduces, thereby making the table squished on one side as shown above

**Required**
Row Action icons column should scale with the screen size and available width responsively allowing the other columns to display in a non-squished manner...

**Comment by Manoj201** [comment]
invalid issue. Data table only support for the desktop design
