### ISSUE TITLE
Alignment issues in Nimble mobile list view

### ISSUE THREAD

**Issue by rasaralaya-nimble-expert** [Nimble-Institute/nimble-design-system#298]
<img width="384" alt="Screenshot 2023-11-17 1215462" src="https://github.com/Nimble-Institute/nimble-design-system/assets/145844108/b8f174b7-22a5-41d4-8345-ad103add6a9c">

**Presently**
Please see above image -> there is a mis-alignment of the details section - when two fields length is breaking the alignment in that scenario

**Required**
 An acceptable way to align the details section

**Comment by Manoj201** [comment]
This is not a lib issue. we can handle this on the project side. Please check the contact mobile screen for ref.
