### ISSUE TITLE
Nimble date picker shows invalid sates when the 'X' button is pressed

### ISSUE THREAD

**Issue by rasaralaya-nimble-expert** [Nimble-Institute/nimble-design-system#306]
<img width="701" alt="Screenshot 2023-11-22 105945" src="https://github.com/Nimble-Institute/nimble-design-system/assets/145844108/316a4d90-7ecd-4b03-8ec1-9ad9ab3539b1">

**Current**

When the nimble-date-picker 'X' button is clicked, it shows invalid date as the entry, and all the dates in the calendar turn into Nan values

**Required**
no Nan values should be shown in the calendar and empty date field should be shown when 'x' is pressed

**Comment by anuja01** [comment]
This needs to be handled from project
