### ISSUE TITLE
Filtering the order of alphabets in data table should take only one filter like name other should off , if name is active i selected email means name should deactivate email should activate

### ISSUE THREAD

**Issue by sharath7178** [Nimble-Institute/nimble-design-system#41]
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/415b00f6-b8e5-4da1-a8ce-eb2692986fa4)

**Comment by Manoj201** [comment]
@sharath7178  I have added one optional prop as isEnableMultipleSort. The default value is false. If you want to enable multiple sort pass isEnableMultipleSort =  true. 

Currently sort working on front-end lodash sort. Please discuss with @rajeshswain424 @NimbleMax what is best for us.
If we want to make the backend side sort I have to modify this a little bit, but not a big change. 

If we want backend side sort please create a new issue and let's modify based on that. Cheers !!
