### ISSUE TITLE
Make to add date picker in the filter of data table

### ISSUE THREAD

**Issue by sharath7178** [Nimble-Institute/nimble-design-system#62]
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/06146ef4-d54e-4457-83a5-da376afda298)

**Comment by Manoj201** [comment]
<img width="278" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/7f9a7f44-4dd1-402e-8fc0-ad5a293577a2">

**Comment by Manoj201** [comment]
@sharath7178 This feature was added and closing this issue. Please pass filterType as date-range.
