### ISSUE TITLE
Autocomplete search behind chip when enough space left

### ISSUE THREAD

**Issue by NimbleMax** [Nimble-Institute/nimble-design-system#72]
<img width="752" alt="Schermafbeelding 2023-08-04 om 13 15 37" src="https://github.com/Nimble-Institute/nimble-design-system/assets/74488289/bb7123b6-044b-4f9c-b920-55e291e4fe1a">

**Comment by Manoj201** [comment]
@NimbleMax we can not fix this issue because we need support from the material UI Team.

**Comment by NimbleMax** [comment]
Are you sure? Let's go over this after my holiday.
