### ISSUE TITLE
Table custom row actions

### ISSUE THREAD

**Issue by NimbleMax** [Nimble-Institute/nimble-design-system#76]
<img width="487" alt="Schermafbeelding 2023-08-04 om 13 39 18" src="https://github.com/Nimble-Institute/nimble-design-system/assets/74488289/a9e9a7f6-4cc9-426d-8d6e-5dd313cd7760">

Option to select 1, 2 or 3 row actions. Option to select the icons you want to use for these actions.

**Comment by Manoj201** [comment]
@NimbleMax Point number 1, we have 3 props developer can enable disable the 3 actions
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/10627a8d-982a-4a98-8946-59c7e52a7251)

**Comment by Manoj201** [comment]
@NimbleMax Point number 2, options to pass images as props, Yes I will do it ASAP. Cheers!!!

**Comment by Manoj201** [comment]
@NimbleMax  This issue is closing, added 3 props to pass custom images to row actions

viewActionicon?: ReactElement<any>;
  editActionicon?: ReactElement<any>;
  deleteActionicon?: ReactElement<any>;

**Comment by NimbleMax** [comment]
Please do not close issues while still open. Please name the props different, it's still delete edit and view. This can be anything

**Comment by Manoj201** [comment]
Now we can pass the below prop to the data table to show custom row actions. 

 rowActions: [
      {
        icon: <img src={what ever image}/>
        onClick: (item: any) => alert('Action 01 click'),
      },
      {
        icon:<svg />,
        onClick: (item: any) => alert('Action 02 click'),
      },
      {
        icon: <img src={}/>,
        onClick: (item: any) => alert('Action 03 click'),
      },
    ]
