### ISSUE TITLE
email column sorting is not happening in data table 

### ISSUE THREAD

**Issue by sharath7178** [Nimble-Institute/nimble-design-system#85]

**Comment by sharath7178** [comment]
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/d3cd569b-9dee-4465-80fe-cfd6c69c0d18)
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/4aaf21d1-ca71-4b1c-b47a-65e9685081e5) see the above image the case sensitive sorting is happening just remove it

**Comment by Manoj201** [comment]
have to discuss this ASAP @sharath7178

**Comment by Manoj201** [comment]
@sharath7178 As we discussed i'm closing this issue. 
Thank you
