### ISSUE TITLE
text feild with multiple lines for sending a comment, make restrictions for letters and it should by props

### ISSUE THREAD

**Issue by sharath7178** [Nimble-Institute/nimble-design-system#99]
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/021046f1-ddaa-4e55-b381-847f79b40f56)

**Comment by Manoj201** [comment]
Below new props added
<img width="960" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/5bc299f1-71ad-428c-9f11-1de3997344e6">
